services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kafka-net
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
       # Optimization settings
      KAFKA_LINGER_MS: 5                                # Low latency message batching
      KAFKA_COMPRESSION_TYPE: gzip                      # Compress messages to reduce size
      KAFKA_NUM_IO_THREADS: 8                           # Increase IO threads for better throughput
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400            # Increase send buffer size
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400         # Increase receive buffer size
      KAFKA_REPLICA_SOCKET_TIMEOUT_MS: 30000            # Increase socket timeout for replicas
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 10000          # Reduce the interval between log flushes
      KAFKA_LOG_RETENTION_HOURS: 24                     # Retain logs for 24 hours
      KAFKA_MESSAGE_MAX_BYTES: 10485760                 # Max message size to 10MB (adjust if needed)
    networks:
      - kafka-net

  client:
    image: ghcr.io/vfiftyfive/shifumi-client:latest
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "50M"
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - kafka-net

  game-logic:
    image: ghcr.io/vfiftyfive/shifumi-server:latest
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
