services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kafka-net
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  client:
    image: vfiftyfive/shifumi-client:latest
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "50M"
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - kafka-net

  game-logic:
    image: vfiftyfive/shifumi-server:latest
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - kafka-net

      
  kafka-test:
    build:
      context: ../../tests
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKER=kafka:9092
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
