apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: shifumi-kafka-pool-dual-role
  namespace: kafka
  labels:
    strimzi.io/cluster: lab
spec:
  template:
    pod:
      metadata:
        annotations:
          intents.otterize.com/service-name: "shifumi-kafka"

  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: lab
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.7.1
    metadataVersion: 3.7-IV4
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    template:
      pod:
        metadata:
          annotations:
            intents.otterize.com/service-name: "kafka-entity-operator"
    topicOperator: {}
    userOperator: {}
