apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/shifumi
  - kafka-broker-cm.yaml
  - namespace.yaml
  - kafka.yaml
  - logger.yaml

patches:
  - path: client.yaml
  - path: server.yaml
