apiVersion: apps/v1
kind: Deployment
metadata:
  name: shifumi-server
spec:
  template:
    spec:
      containers:
      - name: shifumi-server
        imagePullPolicy: Always
        envFrom:
        - configMapRef: 
            name: kafka-broker
