apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shifumi-server
  name: shifumi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shifumi-server
  template:
    metadata:
      labels:
        app: shifumi-server
    spec:
      containers:
      - image: vfiftyfive/shifumi-server
        name: shifumi-server
        ports: 
        - name: shifumi-server
          containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shifumi-server
  name: shifumi-server
spec:
  ports:
  - name: 8082-shifumi-server
    port: 8082
    protocol: TCP
    targetPort: shifumi-server
  selector:
    app: shifumi-server
  type: NodePort



